FROM python:3.11.6-alpine3.18

WORKDIR /backend

EXPOSE 8000

COPY . .

RUN apk update
RUN apk add --no-cache libpq-dev gcc libc-dev
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt
RUN python3 -m pip install gunicorn
RUN cd backend

CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
