FROM python:3.11.6-alpine3.18

WORKDIR /backend

COPY . .

RUN apk update
RUN apk add --no-cache libpq-dev gcc libc-dev
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
