# Generated by Django 4.2.5 on 2023-10-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universeety', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'managed': False},
        ),
    ]
