# Generated by Django 4.2.5 on 2023-10-27 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universeety', '0003_course_universitycourse_alter_university_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'managed': False, 'verbose_name_plural': 'universities'},
        ),
    ]
