export const provinces = {
  aceh: "ChIJvcR8UN-bOTARYMogsoCdAwE",
  "sumatera utara": "ChIJhxxy61r51y8RC8vXCYE-p6w",
  "sumatera selatan": "ChIJLeo1PXWLEC4Rz8QB4gGB_Bg",
  "sumatera barat": "ChIJRUJ08Ey51C8RVTvVdblRsXA",
  bengkulu: "ChIJeZLjNx6wNi4R4bGjxGX7HFE",
  riau: "ChIJdz6xGVhXJy4Rsb21bJQCb4M",
  "kepulauan riau": "ChIJAQuH1E1l2TERvCSFiXW1RnI",
  jambi: "ChIJ2aytzd2IJS4R8E-Q0103c3Q",
  lampung: "ChIJpyKsUwF2Oy4RmrCJX8dYO48",
  "bangka belitung": "ChIJizmlLUMWFy4RuSOEsf04fhI",
  "kalimantan barat": "ChIJu_7rjBcYBS4RoEghTO3sXM0",
  "kalimantan timur": "ChIJkZxNlhBH8S0R13bjLx2wq8Q",
  "kalimantan selatan": "ChIJRbTSvTm33S0RE8GXt1C2fhQ",
  "kalimantan tengah": "ChIJP5a8hrK_4i0Rrmv1g2fV288",
  "kalimantan utara": "ChIJ9wvfNH0GDzIRiLlGaN3wERk",
  banten: "ChIJmbkNxNaKQS4R6bMai6ua074",
  jakarta: "ChIJnUvjRenzaS4RILjULejFAAE",
  "jawa barat": "ChIJf0dSgjnmaC4Rfp2O_FSkGLw",
  "jawa tengah": "ChIJ3RjVnJt1ZS4RRrztj53Rd8M",
  yogyakarta: "ChIJxWtbvYdXei4R8LPIyrKSG20",
  "jawa timur": "ChIJxbXun_eToy0RULh8yvsLAwE",
  bali: "ChIJoQ8Q6NNB0S0RkOYkS7EPkSQ",
  "nusa tenggara timur": "ChIJlzbpqE3yUiwR4Br3yvsLAwE",
  "nusa tenggara barat": "ChIJIe0SGpQNuC0RxXX30MzCZ2k",
  gorontalo: "ChIJSa0hzCXAcTIRIBr3yvsLAwE",
  "sulawesi barat": "ChIJCUS7VCTaki0R8nAzLyC_XOo",
  "sulawesi tengah": "ChIJPS2aZckJiC0RmWLbjP0zbkM",
  "sulawesi tenggara": "ChIJg3FrC97smC0R7aQEn0N8HWI",
  "sulawesi utara": "ChIJMZ4GcEJ1hzIRNbgMmBcWiUU",
  "sulawesi selatan": "ChIJi75r_YD6DC0R8Br3yvsLAwE",
  "maluku utara": "ChIJszIkro6uni0RwBr3yvsLAwE",
  maluku: "ChIJ36EccLq8ES0RUZpkBNvoMF4",
  "papua barat": "ChIJLQviub0KVC0RYsvHxfjBSVM",
  papua: "ChIJc5L_qgQsO2gRc-bvXpxOqes",
};
