FROM python:3.11.6-alpine3.18

WORKDIR /scrapper

COPY . .

RUN apk update
RUN apk add --no-cache libpq-dev gcc libc-dev firefox
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

CMD ["python3", "main.py"]
